/**
 * extracted button text via contents-crawler, ui-dataset.
 * contents-crawler (text) at https://github.com/bridgedxyz/contents-crawler/tree/main/classified_text_crawler
 * ui-dataset (text) at https://github.com/bridgedxyz/ui-dataset/tree/main/text
 */
export const BUTTON_TEXTS_SET_EN = [
    "Add customers",
    "Add a customer",
    "OK",
    "Next",
    "Confirm",
    "Complete",
    "Create",
    "Creaet new teams",
    "Create new Workspace",
    "Continue",
    "Share",
    "Skip",
    "Switch",
    "Send",
    "Send invite link",
    "Cancel",
    "View All",
    "Order",
    "Register",
    "Send Payment PDF to email",
    "Select",
    "Write new note",
    "Read",
    "Sign up for our newsletter",
    "Shop all Bike",
    "Shop all Skate",
    "Shop all Paddle",
    "Shop all Alpine",
    "Shop all Exercise",
    "Shop all Youth",
    "Shop all Apparel",
    "Shop all Gifts",
    "Adult Bikes",
    "Kids Bikes",
    "Dealers",
    "Shop All Bike",
    "Shop All Single-Speed",
    "Exit",
    "Shop All City Bike",
    "Shop All Beach Cruiser",
    "Shop All Hybrid",
    "Shop All Folding",
    "Shop All Youth",
    "Shop All Trailers",
    "Shop All Car // Bike Racks",
    "Shop All Components & Accessories",
    "Shop All Last Chance",
    "Shop All Skate",
    "Shop All Longboard",
    "Shop All Cruiser",
    "Shop All Skateboard",
    "Shop All Protective Gear",
    "Shop All Paddle",
    "Shop All Adult",
    "Shop All Party",
    "Shop All Accessories",
    "Shop All Alpine",
    "Shop All Snow Helmets",
    "Shop All Snow Goggles",
    "Shop All Snowshoes",
    "Shop All Trekking Poles",
    "Shop All Exercise",
    "Shop All Yoga // Exercise Mats",
    "Shop All Yoga Bolsters",
    "Shop All Meditation Cushions",
    "Shop All Exercise Ball & Bases",
    "Shop All Foam Rollers",
    "Shop All Home Gym",
    "Shop All Bike Child Trailers",
    "Shop All Scooters",
    "Shop All Apparel",
    "Shop All Second Nature Collection",
    "Shop All Eco Collection",
    "Shop All Gifts",
    "Shop All Gift Cards",
    "Shop All Gifts under $50",
    "Shop All Gifts under $75",
    "Shop All Gifts under $150",
    "Shop All Gifts under $200",
    "Shop All Gifts $200 and up",
    "Shop Beaumont",
    "Shop All",
    "Shop Paddle",
    "Shop Youth Bikes",
    "Shop Exercise",
    "Shop Adult Bikes",
    "Shop Now",
    "Find a Dealer",
    "Shop Bikes",
    "Shop Skateboards",
    "Shop Yoga Mats",
    "Shop Trekking Poles",
    "Get a Grid",
    "Next",
    "Get API Keys",
    "Contact",
    "Get Started",
    "Developer Docs",
    "Next step",
    "Lapa Ninja",
    "Get the book",
    "View",
    "Reload Page",
    "+",
    "Buy",
    "Shop",
    "Open the app",
    "Try for 14 days",
    "Get started",
    "Book a demo",
    "Start free trial",
    "Book a call",
    "SIGN UP FREE",
    "Yes",
    "No",
    "Submit",
    "This help content & information",
    "General Help Center experience",

]